# Generated by Django 4.0.5 on 2022-06-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_contact_rename_user_profile_userprofileinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_type',
            field=models.CharField(choices=[('educator', 'educator'), ('student', 'student'), ('parent', 'parent')], default='student', max_length=10),
        ),
    ]
